
# job:
#   name: curl -L https://web --output web.html

# # Create a artifacts
# job:
#   artifacts:
#     name: "$CI_JOB_NAME"
#     paths:
#       - binaries/


image: curl

stages:
  - build

build:
  stage: build
  script:
    - curl -o index.html http://Your-AWS-Server-IP
  artifacts:
    paths:
      - index.html

